### ISSUE TITLE
Get release files directly from GitHub, not from custom branches.

### ISSUE THREAD

**Issue by jcstr** [sLite/i3#10]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[x] Other (Please describe in detail)
I'd to get release files directly from GitHub, not from custom branches.
I'm taking care of the AUR package and I consider this as useful.
</pre>

## Current Behavior

I'm getting the content of the package from a custom branch.

## Desired Behavior

I'd to get the latest version of the project from release files.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: N/A
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): N/A
</pre>

**Comment by jcstr** [comment]
Well, forgot to question:
Is this project active?

**Comment by sLite** [comment]
Hi,

I do not use this patched version of i3 myself anymore and i'ts unmaintained.

Progress in vanilla i3 has made it obsolete for me, vanilla i3 has worked flawless for me for over a year now. 

The only thing that i had to get rid of is the plasma desktop. I kill that via my i3 configuration.
But a desktop is of no use in a tiling window manager anyway (imho).

My i3 config has been fine-tuned for all the tools and apps i use over the years, none of those need any patches to i3 anymore.

Best Regards
Daniel

**Comment by jcstr** [comment]
Oh, I see. 

I'll fill a request to delete the package then.

Thanks for your response.
