### ISSUE TITLE
Is multi-monitor support working?

### ISSUE THREAD

**Issue by osa1** [sLite/i3#2]
So I just tried giving a presentation using this i3 distribution and it ended up miserably. For some reason i3 gets stuck in a weird state when I try to connect a second display and only way I could find to reset is to kill Xorg. Ideally, I'd want to use KDE's display settings as before. Any ideas?

Thanks.

**Comment by sLite** [comment]
Hmm, i got no problems with multi-monitor whatsoever.
Also KDE display settings work just fine for my 2 computers with dual monitor setup.
Disabling, rearranging and changing resolutions and such works just fine. Haven't tried with beamers though.

The additional patches in this repo are extremely minimal, it's pretty unlikely they affect anything regarding xrandr.

Can you reproduce this consistently? 
Also you could try to pull the master branch of this repo and try with that. That is the unmodified upstream branch that the other branches are based on. Maybe it's already a bug in the upstream version that this is based on (currently 4.8).
Additionally there is a kde-master branch, that _only_ contains the kde relevant patches (without window icons), you can try that too.

I do plan to bump up the version to current upstream (4.9) soon.

**Comment by osa1** [comment]
This is extremely annoying.. I'm still having this problem and I can reproduce it consistently. I think i3 crashes for some reason.

* If I plug an external monitor, it works fine, however when I unplug, suddenly i3 stops working. i3 window borders are removed, key bindings are not working etc. I can still use KDE key bindings(for example, alt+F2 runs krunner).
* Similar thing happens when I connect a projector, my screen resolution changes to make it same with the projector(I think KDE does something smart here, when I connect a high-res monitor it automatically sets it as an second display, but when I connect a projector it tries to mirror my screen), however i3 again crashes, and window borders gets removed, key bindings stops working etc.

@sLite are you using IRC? Do you mind if I ask a few questions to solve this? External monitor is not a issue but I really need to make it working with projectors.

**Comment by osa1** [comment]
Here's more info:

* I thought maybe i3 is segfaulting, and tried to get a stack trace using gdb. However according to gdb, it's just exiting with return code 1. No segfaults or anything like that.

* I tried to generate a log file, however `i3-dump-log` is not working when i3 is not working, so it's basically useless when you're trying to debug a crash.

**Comment by osa1** [comment]
Yay \o/ I finally fixed it! Here's what I did:

* I stopped kscreen service, it was starting automatically at the startup, I disabled it using System Settings > Service Manager.
* I stopped using kscreen configuration screen and started using `arandr` instead. (not that this step may not be necessary, but it works)

And finally everything seems to work perfectly. I'll try to see if mirror mode is also working. (that's very important for presentation, I think)

**Comment by osa1** [comment]
Last update: I tried kscreen's "unify output"(aka. mirroring) feature and it failed every single time.(i3 crashes) However, I can just place projector's display on top of main display and have a "mirrored" area on my screen, which is good enough for me.

Awesome \o/

**Comment by sLite** [comment]
Thank you for the update :)

I had to present with a projector some days ago for the first time with this version of i3.
It just worked out of the box, i plugged in the projector. KDE asked me what to do and i chose the "automatic" option to detect the display.

It automatically detected the right resolution of the projector and switched it to mirroring mode. Also  unplugging the projector worked without any troubles.

This leades me to the conclusion, that your problem is either hardware/videodriver or KDE related.

I'm on arch linux so i have a very recent version of kde (4.14.6) and an NVIDIA card. This combination seems to play nice with this version of i3 and projectors.

Daniel
